/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOmnihubRouteImport } from './routes/_app/omnihub'
import { Route as AppModulesRouteImport } from './routes/_app/modules'
import { Route as AppInsightaiRouteImport } from './routes/_app/insightai'
import { Route as AppExecutiveRouteImport } from './routes/_app/executive'
import { Route as AppCrmRouteImport } from './routes/_app/crm'
import { Route as AppBotifyRouteImport } from './routes/_app/botify'
import { Route as AppAdsRouteImport } from './routes/_app/ads'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads.index'
import { Route as AppJourneysIndexRouteImport } from './routes/_app/journeys.index'
import { Route as AppSettingsLineHealthRouteImport } from './routes/_app/settings.line-health'
import { Route as AppSettingsBudgetRouteImport } from './routes/_app/settings.budget'
import { Route as AppSettingsBrokersRouteImport } from './routes/_app/settings.brokers'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings.audit'
import { Route as AppSettingsAntiFatigueRouteImport } from './routes/_app/settings.anti-fatigue'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads.$leadId'
import { Route as AppJourneysBuilderRouteImport } from './routes/_app/journeys.builder'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOmnihubRoute = AppOmnihubRouteImport.update({
  id: '/omnihub',
  path: '/omnihub',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRoute = AppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightaiRoute = AppInsightaiRouteImport.update({
  id: '/insightai',
  path: '/insightai',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutiveRoute = AppExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppBotifyRoute = AppBotifyRouteImport.update({
  id: '/botify',
  path: '/botify',
  getParentRoute: () => AppRoute,
} as any)
const AppAdsRoute = AppAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysIndexRoute = AppJourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLineHealthRoute = AppSettingsLineHealthRouteImport.update({
  id: '/line-health',
  path: '/line-health',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBudgetRoute = AppSettingsBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBrokersRoute = AppSettingsBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAntiFatigueRoute = AppSettingsAntiFatigueRouteImport.update({
  id: '/anti-fatigue',
  path: '/anti-fatigue',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)
const AppJourneysBuilderRoute = AppJourneysBuilderRouteImport.update({
  id: '/journeys/builder',
  path: '/journeys/builder',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ads': typeof AppAdsRoute
  '/botify': typeof AppBotifyRoute
  '/crm': typeof AppCrmRoute
  '/executive': typeof AppExecutiveRoute
  '/insightai': typeof AppInsightaiRoute
  '/modules': typeof AppModulesRoute
  '/omnihub': typeof AppOmnihubRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/journeys/builder': typeof AppJourneysBuilderRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/settings/anti-fatigue': typeof AppSettingsAntiFatigueRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/brokers': typeof AppSettingsBrokersRoute
  '/settings/budget': typeof AppSettingsBudgetRoute
  '/settings/line-health': typeof AppSettingsLineHealthRoute
  '/journeys/': typeof AppJourneysIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ads': typeof AppAdsRoute
  '/botify': typeof AppBotifyRoute
  '/crm': typeof AppCrmRoute
  '/executive': typeof AppExecutiveRoute
  '/insightai': typeof AppInsightaiRoute
  '/modules': typeof AppModulesRoute
  '/omnihub': typeof AppOmnihubRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/': typeof AppIndexRoute
  '/journeys/builder': typeof AppJourneysBuilderRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/settings/anti-fatigue': typeof AppSettingsAntiFatigueRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/brokers': typeof AppSettingsBrokersRoute
  '/settings/budget': typeof AppSettingsBudgetRoute
  '/settings/line-health': typeof AppSettingsLineHealthRoute
  '/journeys': typeof AppJourneysIndexRoute
  '/leads': typeof AppLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/ads': typeof AppAdsRoute
  '/_app/botify': typeof AppBotifyRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/executive': typeof AppExecutiveRoute
  '/_app/insightai': typeof AppInsightaiRoute
  '/_app/modules': typeof AppModulesRoute
  '/_app/omnihub': typeof AppOmnihubRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/journeys/builder': typeof AppJourneysBuilderRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/settings/anti-fatigue': typeof AppSettingsAntiFatigueRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/brokers': typeof AppSettingsBrokersRoute
  '/_app/settings/budget': typeof AppSettingsBudgetRoute
  '/_app/settings/line-health': typeof AppSettingsLineHealthRoute
  '/_app/journeys/': typeof AppJourneysIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/ads'
    | '/botify'
    | '/crm'
    | '/executive'
    | '/insightai'
    | '/modules'
    | '/omnihub'
    | '/settings'
    | '/journeys/builder'
    | '/leads/$leadId'
    | '/settings/anti-fatigue'
    | '/settings/audit'
    | '/settings/brokers'
    | '/settings/budget'
    | '/settings/line-health'
    | '/journeys/'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/ads'
    | '/botify'
    | '/crm'
    | '/executive'
    | '/insightai'
    | '/modules'
    | '/omnihub'
    | '/settings'
    | '/'
    | '/journeys/builder'
    | '/leads/$leadId'
    | '/settings/anti-fatigue'
    | '/settings/audit'
    | '/settings/brokers'
    | '/settings/budget'
    | '/settings/line-health'
    | '/journeys'
    | '/leads'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/ads'
    | '/_app/botify'
    | '/_app/crm'
    | '/_app/executive'
    | '/_app/insightai'
    | '/_app/modules'
    | '/_app/omnihub'
    | '/_app/settings'
    | '/_app/'
    | '/_app/journeys/builder'
    | '/_app/leads/$leadId'
    | '/_app/settings/anti-fatigue'
    | '/_app/settings/audit'
    | '/_app/settings/brokers'
    | '/_app/settings/budget'
    | '/_app/settings/line-health'
    | '/_app/journeys/'
    | '/_app/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/omnihub': {
      id: '/_app/omnihub'
      path: '/omnihub'
      fullPath: '/omnihub'
      preLoaderRoute: typeof AppOmnihubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules': {
      id: '/_app/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AppModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insightai': {
      id: '/_app/insightai'
      path: '/insightai'
      fullPath: '/insightai'
      preLoaderRoute: typeof AppInsightaiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/executive': {
      id: '/_app/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof AppExecutiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/botify': {
      id: '/_app/botify'
      path: '/botify'
      fullPath: '/botify'
      preLoaderRoute: typeof AppBotifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ads': {
      id: '/_app/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AppAdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys/': {
      id: '/_app/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof AppJourneysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/line-health': {
      id: '/_app/settings/line-health'
      path: '/line-health'
      fullPath: '/settings/line-health'
      preLoaderRoute: typeof AppSettingsLineHealthRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/budget': {
      id: '/_app/settings/budget'
      path: '/budget'
      fullPath: '/settings/budget'
      preLoaderRoute: typeof AppSettingsBudgetRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/brokers': {
      id: '/_app/settings/brokers'
      path: '/brokers'
      fullPath: '/settings/brokers'
      preLoaderRoute: typeof AppSettingsBrokersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/anti-fatigue': {
      id: '/_app/settings/anti-fatigue'
      path: '/anti-fatigue'
      fullPath: '/settings/anti-fatigue'
      preLoaderRoute: typeof AppSettingsAntiFatigueRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journeys/builder': {
      id: '/_app/journeys/builder'
      path: '/journeys/builder'
      fullPath: '/journeys/builder'
      preLoaderRoute: typeof AppJourneysBuilderRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAntiFatigueRoute: typeof AppSettingsAntiFatigueRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBrokersRoute: typeof AppSettingsBrokersRoute
  AppSettingsBudgetRoute: typeof AppSettingsBudgetRoute
  AppSettingsLineHealthRoute: typeof AppSettingsLineHealthRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAntiFatigueRoute: AppSettingsAntiFatigueRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBrokersRoute: AppSettingsBrokersRoute,
  AppSettingsBudgetRoute: AppSettingsBudgetRoute,
  AppSettingsLineHealthRoute: AppSettingsLineHealthRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAdsRoute: typeof AppAdsRoute
  AppBotifyRoute: typeof AppBotifyRoute
  AppCrmRoute: typeof AppCrmRoute
  AppExecutiveRoute: typeof AppExecutiveRoute
  AppInsightaiRoute: typeof AppInsightaiRoute
  AppModulesRoute: typeof AppModulesRoute
  AppOmnihubRoute: typeof AppOmnihubRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppJourneysBuilderRoute: typeof AppJourneysBuilderRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppJourneysIndexRoute: typeof AppJourneysIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdsRoute: AppAdsRoute,
  AppBotifyRoute: AppBotifyRoute,
  AppCrmRoute: AppCrmRoute,
  AppExecutiveRoute: AppExecutiveRoute,
  AppInsightaiRoute: AppInsightaiRoute,
  AppModulesRoute: AppModulesRoute,
  AppOmnihubRoute: AppOmnihubRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppJourneysBuilderRoute: AppJourneysBuilderRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppJourneysIndexRoute: AppJourneysIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
